// --Directions
// Print out the n-th entry in the fibonacci series.
// The fibonacci series is an ordering of numbers where each number is the sum of the preceding two.
// For example the sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34] forms the first ten entries in the 
// fibonacci series.
//-- Example
// fib(4) === 3



function fib(n){
    const result =[0, 1];//These numbers cannot be generated by a for loop,
     //while meeting the fibonacci algorithm requirement, since they each  don't have two previous entries
     // so we manually add 0 and 1 to the result set. Then now i will begin from index 2.

    for(let i=2; i <= n; i++){
        const a = result[i-1]; //We are getting the value whose index is immediately before the current by 1
        const b = result[i-2]; // The values whose index is secondly behind the current value i
        result.push(a+b);
    }
    
    console.log(result);
    console.log("The nth result is :", result[n])
}

fib(9);